import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/router";
import { Inter } from '@next/font/google'
import { Button } from "@nextui-org/react";


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>New Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-4xl font-semibold ">Welcome to New Me!</h1>
        <Button onClick={()=>router.push('/register')} color="primary" auto>
        Create user
        </Button>
      </div>
    </>
  )
}
